### ISSUE TITLE
TypeError 

### ISSUE THREAD

**Issue by pietromosca1994** [DIMO-Network/dimo-streams-demo#6]
I am trying to run the demo however I get this error
```
WARN [2024-05-10T09:03:28.427] (fetchAirportCodeFromCdn  ): fetch failed
    err: {
      "type": "TypeError",
      "message": "fetch failed: read ECONNRESET",
      "stack":
          TypeError: fetch failed
              at Object.fetch (node:internal/deps/undici/undici:11413:11)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at fetchHeader (C:\Users\pmosca\Desktop\repos\dimo-streams-demo\node_modules\@streamr\cdn-location\src\fetchAirportCodeFromCdn.ts:10:22)
              at fetchAirportCodeFromAmazon (C:\Users\pmosca\Desktop\repos\dimo-streams-demo\node_modules\@streamr\cdn-location\src\fetchAirportCodeFromCdn.ts:17:20)
              at fetchAirportCodeFromCdn (C:\Users\pmosca\Desktop\repos\dimo-streams-demo\node_modules\@streamr\cdn-location\src\fetchAirportCodeFromCdn.ts:53:16)
              at getLocalRegion (C:\Users\pmosca\Desktop\repos\dimo-streams-demo\node_modules\@streamr\cdn-location\src\getLocalRegion.ts:29:23)
              at DhtNode.start (C:\Users\pmosca\Desktop\repos\dimo-streams-demo\node_modules\@streamr\dht\src\dht\DhtNode.ts:193:27)
              at NetworkStack.start (C:\Users\pmosca\Desktop\repos\dimo-streams-demo\node_modules\@streamr\trackerless-network\src\NetworkStack.ts:104:9)
              at NetworkNode.start (C:\Users\pmosca\Desktop\repos\dimo-streams-demo\node_modules\@streamr\trackerless-network\src\NetworkNode.ts:41:9)
              at <anonymous> (C:\Users\pmosca\Desktop\repos\dimo-streams-demo\node_modules\@streamr\src\NetworkNodeFacade.ts:156:17)
          caused by: Error: read ECONNRESET
              at __node_internal_captureLargerStackTrace (node:internal/errors:490:5)
              at __node_internal_errnoException (node:internal/errors:620:12)
              at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
    }
INFO [2024-05-10T09:03:30.992] (StreamrNode              ): Starting new StreamrNode with id d2b6b205f6b4c5450f4e7e7bc6dc0deb62c4641c
```

I followed the instructions in the README however I am not able to get the streams like I was able to do yesterday...
Anyone able to help with this? Thank you very much in advance!

**Comment by zer0stars** [comment]
Hey Pietro,

Can you double check the node version you are using? I was able to reproduce this on node@16, and this error does not occur on node@20.

**Comment by jamesliupenn** [comment]
@pietromosca1994 are you still dealing with this issue? If you're interested in building apps using streams, I would highly suggest getting a Developer License 👍🏻
